import type { FoodItem } from "./seed-foods";

// Carman's 澳洲蛋白棒系列 — nutrition per serving from Shopee product labels
// Source: https://shopee.tw/i.227904899.23635594346
export const carmansFoods: FoodItem[] = [
  {
    name: "Carman's 莓果希臘優格蛋白棒",
    brand: "Carman's",
    source: "user" as const,
    servingSize: 40,
    servingUnit: "g",
    householdServing: "1 條",
    calories: 179,
    nutrients: {
      protein: 10.9,
      fat: 9.6,
      saturatedFat: 2.2,
      transFat: 0,
      carbs: 13.3,
      sugar: 9.2,
      fiber: 1.9,
      sodium: 70,
    },
  },
  {
    name: "Carman's 黑可可蔓越莓蛋白棒",
    brand: "Carman's",
    source: "user" as const,
    servingSize: 40,
    servingUnit: "g",
    householdServing: "1 條",
    calories: 197,
    nutrients: {
      protein: 10.5,
      fat: 10.7,
      saturatedFat: 2.2,
      transFat: 0,
      carbs: 16,
      sugar: 9.2,
      fiber: 2.6,
      sodium: 52,
    },
  },
  {
    name: "Carman's 可可餅乾大豆蛋白棒",
    brand: "Carman's",
    source: "user" as const,
    servingSize: 40,
    servingUnit: "g",
    householdServing: "1 條",
    calories: 188,
    nutrients: {
      protein: 10,
      fat: 10,
      saturatedFat: 3.4,
      transFat: 0,
      carbs: 16.2,
      sugar: 7.2,
      fiber: 3.3,
      sodium: 94,
    },
  },
  {
    name: "Carman's 焦鹽黑可可大豆蛋白棒",
    brand: "Carman's",
    source: "user" as const,
    servingSize: 40,
    servingUnit: "g",
    householdServing: "1 條",
    calories: 205,
    nutrients: {
      protein: 11.1,
      fat: 11.6,
      saturatedFat: 2.6,
      transFat: 0,
      carbs: 16.1,
      sugar: 6.8,
      fiber: 4,
      sodium: 60,
    },
  },
  {
    name: "Carman's 花生腰果優格蛋白棒",
    brand: "Carman's",
    source: "user" as const,
    servingSize: 40,
    servingUnit: "g",
    householdServing: "1 條",
    calories: 198,
    nutrients: {
      protein: 10.2,
      fat: 11.6,
      saturatedFat: 3.6,
      transFat: 0,
      carbs: 17.1,
      sugar: 6,
      fiber: 1.4,
      sodium: 55,
    },
  },
  {
    name: "Carman's 覆盆莓開心果蛋白棒",
    brand: "Carman's",
    source: "user" as const,
    servingSize: 30,
    servingUnit: "g",
    householdServing: "1 條",
    calories: 133,
    nutrients: {
      protein: 7.7,
      fat: 7.3,
      saturatedFat: 1.1,
      transFat: 0,
      carbs: 11.2,
      sugar: 3.3,
      fiber: 4.1,
      sodium: 55,
    },
  },
  {
    name: "Carman's 冰拿鐵蛋白棒",
    brand: "Carman's",
    source: "user" as const,
    servingSize: 40,
    servingUnit: "g",
    householdServing: "1 條",
    calories: 190,
    nutrients: {
      protein: 10.4,
      fat: 9.9,
      saturatedFat: 2.5,
      transFat: 0,
      carbs: 15.7,
      sugar: 8.2,
      fiber: 1.6,
      sodium: 93,
    },
  },
];
