import type { FoodItem } from "./seed-foods";

// 十雞食堂 Chicken Food — estimated nutrition per serving
// Menu: chicken rice bentos with rice cooked in chicken broth + sides
// Estimates based on typical Taiwanese chicken bento nutrition data
export const chickenFoodFoods: FoodItem[] = [
  // ========== 便當 Bento (主食 + 配菜 + 雞湯飯) ==========
  {
    name: "去骨海南雞腿飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 500,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 580,
    nutrients: { protein: 35, fat: 18, carbs: 70, fiber: 2, sodium: 900, potassium: 400 },
  },
  {
    name: "泰式椒麻雞腿飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 500,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 650,
    nutrients: { protein: 32, fat: 24, carbs: 72, fiber: 2, sodium: 1000, potassium: 380 },
  },
  {
    name: "日式唐揚雞飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 500,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 680,
    nutrients: { protein: 30, fat: 28, carbs: 75, fiber: 2, sodium: 950, potassium: 360 },
  },
  {
    name: "泰式綠咖哩雞飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 500,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 630,
    nutrients: { protein: 28, fat: 22, carbs: 72, fiber: 3, sodium: 1050, potassium: 420 },
  },
  {
    name: "泰式打拋雞飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 480,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 550,
    nutrients: { protein: 26, fat: 16, carbs: 70, fiber: 2, sodium: 980, potassium: 380 },
  },
  {
    name: "祕製去骨麻辣雞飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 500,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 610,
    nutrients: { protein: 30, fat: 20, carbs: 70, fiber: 2, sodium: 1100, potassium: 390 },
  },
  {
    name: "酥炸雞腿飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 500,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 710,
    nutrients: { protein: 32, fat: 30, carbs: 75, fiber: 2, sodium: 920, potassium: 370 },
  },
  {
    name: "老滷雞腿飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 500,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 610,
    nutrients: { protein: 34, fat: 18, carbs: 72, fiber: 2, sodium: 1050, potassium: 420 },
  },
  {
    name: "酥炸雞排飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 480,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 650,
    nutrients: { protein: 30, fat: 25, carbs: 75, fiber: 2, sodium: 900, potassium: 350 },
  },
  {
    name: "酥炸雞柳飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 470,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 630,
    nutrients: { protein: 28, fat: 23, carbs: 75, fiber: 2, sodium: 880, potassium: 340 },
  },
  {
    name: "雞絲飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 400,
    servingUnit: "g",
    householdServing: "1 便當",
    calories: 460,
    nutrients: { protein: 22, fat: 8, carbs: 70, fiber: 1, sodium: 750, potassium: 300 },
  },

  // ========== 單品 Side Items ==========
  {
    name: "菜飯",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 350,
    servingUnit: "g",
    householdServing: "1 份",
    calories: 360,
    nutrients: { protein: 8, fat: 6, carbs: 62, fiber: 4, sodium: 600, potassium: 280 },
  },
  {
    name: "白飯（雞湯飯）",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 200,
    servingUnit: "g",
    householdServing: "1 碗",
    calories: 260,
    nutrients: { protein: 5, fat: 1, carbs: 58, fiber: 0.5, sodium: 150, potassium: 50 },
  },
  {
    name: "半顆蛋",
    brand: "十雞食堂",
    source: "user" as const,
    servingSize: 30,
    servingUnit: "g",
    householdServing: "半顆",
    calories: 40,
    nutrients: { protein: 3, fat: 3, carbs: 0.5, fiber: 0, sodium: 70, potassium: 30 },
  },
];
