import type { FoodItem } from "./seed-foods";

// 弍食穗健康餐盒 — 台北松山/內湖
// 幸福水煮區 + 獨門料理區
// 餐盒含紫米飯、水煮蛋、季節蔬菜
// 營養為估算值（健康餐盒典型組成）
export const erShiSuiFoods: FoodItem[] = [
  // ── 幸福水煮區 餐盒 ──
  {
    name: "水煮嫩雞胸 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 420,
    nutrients: { protein: 38, fat: 8, carbs: 48, fiber: 5, sodium: 580 },
    metadata: { price: 115, category: "幸福水煮區" },
  },
  {
    name: "清爽豬肉片 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 460,
    nutrients: { protein: 32, fat: 13, carbs: 50, fiber: 5, sodium: 620 },
    metadata: { price: 110, category: "幸福水煮區" },
  },
  {
    name: "極鮮虱目魚柳 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 440,
    nutrients: { protein: 34, fat: 10, carbs: 50, fiber: 5, sodium: 600 },
    metadata: { price: 125, category: "幸福水煮區" },
  },
  {
    name: "嫩雞胸+清爽豬 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~420g)",
    calories: 450,
    nutrients: { protein: 36, fat: 11, carbs: 48, fiber: 5, sodium: 610 },
    metadata: { price: 120, category: "幸福水煮區" },
  },
  {
    name: "清爽豬+虱目魚柳 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~420g)",
    calories: 455,
    nutrients: { protein: 34, fat: 12, carbs: 50, fiber: 5, sodium: 620 },
    metadata: { price: 120, category: "幸福水煮區" },
  },
  {
    name: "嫩雞胸+壽喜牛 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~420g)",
    calories: 480,
    nutrients: { protein: 37, fat: 13, carbs: 50, fiber: 4, sodium: 680 },
    metadata: { price: 125, category: "幸福水煮區" },
  },
  // ── 幸福水煮區 單點 ──
  {
    name: "水煮嫩雞胸",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~150g)",
    calories: 165,
    nutrients: { protein: 31, fat: 3.5, carbs: 0, fiber: 0, sodium: 250 },
    metadata: { price: 55, category: "幸福水煮區 單點" },
  },
  {
    name: "清爽豬肉片",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~130g)",
    calories: 195,
    nutrients: { protein: 25, fat: 10, carbs: 0, fiber: 0, sodium: 280 },
    metadata: { price: 50, category: "幸福水煮區 單點" },
  },
  {
    name: "極鮮虱目魚柳",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~130g)",
    calories: 180,
    nutrients: { protein: 28, fat: 7, carbs: 0, fiber: 0, sodium: 260 },
    metadata: { price: 65, category: "幸福水煮區 單點" },
  },
  // ── 獨門料理區 餐盒 ──
  {
    name: "薑汁壽喜牛 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 510,
    nutrients: { protein: 35, fat: 16, carbs: 52, fiber: 4, sodium: 720 },
    metadata: { price: 130, category: "獨門料理區" },
  },
  {
    name: "蒜味塔香牛 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 520,
    nutrients: { protein: 35, fat: 17, carbs: 52, fiber: 4, sodium: 730 },
    metadata: { price: 130, category: "獨門料理區" },
  },
  {
    name: "古早味棒棒腿 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 490,
    nutrients: { protein: 33, fat: 15, carbs: 52, fiber: 4, sodium: 680 },
    metadata: { price: 115, category: "獨門料理區" },
  },
  {
    name: "香煎鱸魚排 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 460,
    nutrients: { protein: 35, fat: 12, carbs: 48, fiber: 5, sodium: 620 },
    metadata: { price: 130, category: "獨門料理區" },
  },
  {
    name: "泰式酸辣豬 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 480,
    nutrients: { protein: 32, fat: 14, carbs: 52, fiber: 5, sodium: 700 },
    metadata: { price: 120, category: "獨門料理區" },
  },
  {
    name: "蔬蔬炖菇菇 餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~380g)",
    calories: 350,
    nutrients: { protein: 15, fat: 8, carbs: 55, fiber: 8, sodium: 500 },
    metadata: { price: 120, category: "獨門料理區" },
  },
  {
    name: "菜飯餐盒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~300g)",
    calories: 280,
    nutrients: { protein: 10, fat: 6, carbs: 48, fiber: 6, sodium: 400 },
    metadata: { price: 60, category: "獨門料理區" },
  },
  // ── 獨門料理區 單點 ──
  {
    name: "薑汁壽喜牛",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~140g)",
    calories: 220,
    nutrients: { protein: 28, fat: 12, carbs: 3, fiber: 0, sodium: 380 },
    metadata: { price: 70, category: "獨門料理區 單點" },
  },
  {
    name: "蒜味塔香牛",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~140g)",
    calories: 230,
    nutrients: { protein: 28, fat: 13, carbs: 3, fiber: 0, sodium: 390 },
    metadata: { price: 70, category: "獨門料理區 單點" },
  },
  {
    name: "古早味棒棒腿",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~120g)",
    calories: 200,
    nutrients: { protein: 26, fat: 10, carbs: 2, fiber: 0, sodium: 350 },
    metadata: { price: 55, category: "獨門料理區 單點" },
  },
  {
    name: "香煎鱸魚排",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~130g)",
    calories: 185,
    nutrients: { protein: 30, fat: 7, carbs: 0, fiber: 0, sodium: 280 },
    metadata: { price: 70, category: "獨門料理區 單點" },
  },
  {
    name: "泰式酸辣豬",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~130g)",
    calories: 200,
    nutrients: { protein: 25, fat: 10, carbs: 3, fiber: 0, sodium: 350 },
    metadata: { price: 60, category: "獨門料理區 單點" },
  },
  // ── 單點區 ──
  {
    name: "香Q紫米飯",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "一份 (~150g)",
    calories: 220,
    nutrients: { protein: 5, fat: 1, carbs: 48, fiber: 2, sodium: 10 },
    metadata: { price: 15, category: "單點區" },
  },
  {
    name: "白玉水煮蛋",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "顆",
    householdServing: "一顆 (~50g)",
    calories: 70,
    nutrients: { protein: 6, fat: 5, carbs: 0.5, fiber: 0, sodium: 60 },
    metadata: { price: 15, category: "單點區" },
  },
  {
    name: "香甜玉米粒",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "一份 (~80g)",
    calories: 85,
    nutrients: { protein: 3, fat: 1, carbs: 18, fiber: 2, sodium: 15 },
    metadata: { price: 15, category: "單點區" },
  },
  {
    name: "韓式泡菜",
    brand: "弍食穗",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "一份 (~50g)",
    calories: 20,
    nutrients: { protein: 1, fat: 0.5, carbs: 3, fiber: 1, sodium: 350 },
    metadata: { price: 20, category: "單點區" },
  },
];
