import type { FoodItem } from "./seed-foods";

// 極限餐盒 Power Peak — 台北內湖
// 餐盒系列 + 螺旋麵沙拉系列 + 單點系列 + 湯品 + 飲品
// 營養為估算值（健康餐盒典型組成）
export const powerPeakFoods: FoodItem[] = [
  // ── 餐盒系列 Main Dishes ──
  {
    name: "極限水煮嫩雞胸 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 430,
    nutrients: { protein: 40, fat: 7, carbs: 50, fiber: 5, sodium: 560 },
    metadata: { price: 125, category: "餐盒系列" },
  },
  {
    name: "蔥鹽嫩雞胸 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 440,
    nutrients: { protein: 38, fat: 9, carbs: 50, fiber: 5, sodium: 620 },
    metadata: { price: 125, category: "餐盒系列" },
  },
  {
    name: "椒麻嫩雞胸 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 460,
    nutrients: { protein: 38, fat: 11, carbs: 50, fiber: 5, sodium: 650 },
    metadata: { price: 125, category: "餐盒系列" },
  },
  {
    name: "蒜蓉梅花豬 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 490,
    nutrients: { protein: 32, fat: 15, carbs: 52, fiber: 5, sodium: 660 },
    metadata: { price: 130, category: "餐盒系列" },
  },
  {
    name: "胡麻梅花豬 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 500,
    nutrients: { protein: 32, fat: 16, carbs: 52, fiber: 5, sodium: 640 },
    metadata: { price: 130, category: "餐盒系列" },
  },
  {
    name: "法式香草烤雞腿 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~420g)",
    calories: 530,
    nutrients: { protein: 35, fat: 18, carbs: 52, fiber: 4, sodium: 680 },
    metadata: { price: 145, category: "餐盒系列" },
  },
  {
    name: "義式爐烤鮭魚 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 520,
    nutrients: { protein: 36, fat: 18, carbs: 48, fiber: 5, sodium: 580 },
    metadata: { price: 190, category: "餐盒系列" },
  },
  {
    name: "義式番茄燉牛腱 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~420g)",
    calories: 510,
    nutrients: { protein: 36, fat: 15, carbs: 52, fiber: 5, sodium: 700 },
    metadata: { price: 170, category: "餐盒系列" },
  },
  {
    name: "鮮菇佐時蔬 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~380g)",
    calories: 360,
    nutrients: { protein: 15, fat: 8, carbs: 55, fiber: 8, sodium: 480 },
    metadata: { price: 130, category: "餐盒系列" },
  },
  {
    name: "低脂泰式打拋豬 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 470,
    nutrients: { protein: 33, fat: 12, carbs: 52, fiber: 5, sodium: 720 },
    metadata: { price: 130, category: "餐盒系列" },
  },
  {
    name: "低脂麻婆豆腐雞 餐盒",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~400g)",
    calories: 450,
    nutrients: { protein: 35, fat: 11, carbs: 50, fiber: 5, sodium: 700 },
    metadata: { price: 130, category: "餐盒系列" },
  },
  // ── 螺旋麵沙拉系列 Salad ──
  {
    name: "極限水煮嫩雞胸沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~380g)",
    calories: 400,
    nutrients: { protein: 38, fat: 10, carbs: 42, fiber: 6, sodium: 520 },
    metadata: { price: 175, category: "螺旋麵沙拉系列" },
  },
  {
    name: "蔥鹽嫩雞胸沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~380g)",
    calories: 410,
    nutrients: { protein: 36, fat: 12, carbs: 42, fiber: 6, sodium: 580 },
    metadata: { price: 175, category: "螺旋麵沙拉系列" },
  },
  {
    name: "椒麻嫩雞胸沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~380g)",
    calories: 430,
    nutrients: { protein: 36, fat: 14, carbs: 42, fiber: 6, sodium: 610 },
    metadata: { price: 195, category: "螺旋麵沙拉系列" },
  },
  {
    name: "蒜蓉梅花豬沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~380g)",
    calories: 460,
    nutrients: { protein: 30, fat: 18, carbs: 44, fiber: 6, sodium: 620 },
    metadata: { price: 180, category: "螺旋麵沙拉系列" },
  },
  {
    name: "胡麻梅花豬沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~380g)",
    calories: 470,
    nutrients: { protein: 30, fat: 19, carbs: 44, fiber: 6, sodium: 600 },
    metadata: { price: 180, category: "螺旋麵沙拉系列" },
  },
  {
    name: "法式香草烤雞腿沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~400g)",
    calories: 500,
    nutrients: { protein: 33, fat: 21, carbs: 44, fiber: 5, sodium: 640 },
    metadata: { price: 180, category: "螺旋麵沙拉系列" },
  },
  {
    name: "義式爐烤鮭魚沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~380g)",
    calories: 490,
    nutrients: { protein: 34, fat: 21, carbs: 40, fiber: 6, sodium: 540 },
    metadata: { price: 240, category: "螺旋麵沙拉系列" },
  },
  {
    name: "義式番茄燉牛腱沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~400g)",
    calories: 480,
    nutrients: { protein: 34, fat: 18, carbs: 44, fiber: 6, sodium: 660 },
    metadata: { price: 210, category: "螺旋麵沙拉系列" },
  },
  {
    name: "鮮菇佐時蔬沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~360g)",
    calories: 330,
    nutrients: { protein: 13, fat: 10, carbs: 48, fiber: 8, sodium: 440 },
    metadata: { price: 180, category: "螺旋麵沙拉系列" },
  },
  {
    name: "低脂泰式打拋豬沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~380g)",
    calories: 440,
    nutrients: { protein: 31, fat: 15, carbs: 44, fiber: 6, sodium: 680 },
    metadata: { price: 180, category: "螺旋麵沙拉系列" },
  },
  {
    name: "低脂麻婆豆腐雞沙拉",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個沙拉盒 (~380g)",
    calories: 420,
    nutrients: { protein: 33, fat: 14, carbs: 42, fiber: 6, sodium: 660 },
    metadata: { price: 180, category: "螺旋麵沙拉系列" },
  },
  // ── 單點系列 Sides ──
  {
    name: "極限水煮嫩雞胸",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~150g)",
    calories: 165,
    nutrients: { protein: 31, fat: 3.5, carbs: 0, fiber: 0, sodium: 250 },
    metadata: { price: 75, category: "單點系列" },
  },
  {
    name: "椒麻嫩雞胸",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~150g)",
    calories: 185,
    nutrients: { protein: 30, fat: 6, carbs: 2, fiber: 0, sodium: 320 },
    metadata: { price: 75, category: "單點系列" },
  },
  {
    name: "蔥鹽嫩雞胸",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~150g)",
    calories: 175,
    nutrients: { protein: 30, fat: 5, carbs: 1, fiber: 0, sodium: 350 },
    metadata: { price: 75, category: "單點系列" },
  },
  {
    name: "蒜蓉梅花豬",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~130g)",
    calories: 210,
    nutrients: { protein: 24, fat: 12, carbs: 2, fiber: 0, sodium: 320 },
    metadata: { price: 80, category: "單點系列" },
  },
  {
    name: "胡麻梅花豬",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~130g)",
    calories: 220,
    nutrients: { protein: 24, fat: 13, carbs: 3, fiber: 0, sodium: 300 },
    metadata: { price: 80, category: "單點系列" },
  },
  {
    name: "法式香草烤雞腿",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~160g)",
    calories: 260,
    nutrients: { protein: 28, fat: 16, carbs: 2, fiber: 0, sodium: 350 },
    metadata: { price: 95, category: "單點系列" },
  },
  {
    name: "義式爐烤鮭魚",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~140g)",
    calories: 280,
    nutrients: { protein: 30, fat: 17, carbs: 1, fiber: 0, sodium: 280 },
    metadata: { price: 140, category: "單點系列" },
  },
  {
    name: "義式番茄燉牛腱",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~150g)",
    calories: 240,
    nutrients: { protein: 30, fat: 12, carbs: 4, fiber: 1, sodium: 380 },
    metadata: { price: 120, category: "單點系列" },
  },
  {
    name: "鮮菇佐時蔬",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~120g)",
    calories: 80,
    nutrients: { protein: 5, fat: 3, carbs: 10, fiber: 3, sodium: 200 },
    metadata: { price: 80, category: "單點系列" },
  },
  {
    name: "低脂泰式打拋豬",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~130g)",
    calories: 195,
    nutrients: { protein: 26, fat: 9, carbs: 3, fiber: 0, sodium: 380 },
    metadata: { price: 80, category: "單點系列" },
  },
  {
    name: "低脂麻婆豆腐雞",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "單點一份 (~140g)",
    calories: 180,
    nutrients: { protein: 28, fat: 7, carbs: 4, fiber: 1, sodium: 360 },
    metadata: { price: 80, category: "單點系列" },
  },
  {
    name: "溏心蛋",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "顆",
    householdServing: "一顆 (~50g)",
    calories: 70,
    nutrients: { protein: 6, fat: 5, carbs: 0.5, fiber: 0, sodium: 180 },
    metadata: { price: 30, category: "單點系列" },
  },
  {
    name: "紅藜麥飯",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "一份 (~150g)",
    calories: 230,
    nutrients: { protein: 6, fat: 1.5, carbs: 48, fiber: 3, sodium: 10 },
    metadata: { price: 15, category: "單點系列" },
  },
  {
    name: "青菜",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "份",
    householdServing: "一份 (~100g)",
    calories: 45,
    nutrients: { protein: 3, fat: 1.5, carbs: 5, fiber: 3, sodium: 150 },
    metadata: { price: 45, category: "單點系列" },
  },
  // ── 湯品 Soup ──
  {
    name: "義式番茄蔬菜湯",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "碗",
    householdServing: "一碗 (~300ml)",
    calories: 80,
    nutrients: { protein: 3, fat: 2, carbs: 12, fiber: 3, sodium: 450 },
    metadata: { price: 45, category: "湯品" },
  },
  {
    name: "菌菇濃湯",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "碗",
    householdServing: "一碗 (~300ml)",
    calories: 120,
    nutrients: { protein: 4, fat: 6, carbs: 13, fiber: 2, sodium: 480 },
    metadata: { price: 45, category: "湯品" },
  },
  // ── 飲品 Drinks ──
  {
    name: "南非國寶茶",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "杯",
    householdServing: "一杯 (~500ml)",
    calories: 0,
    nutrients: { protein: 0, fat: 0, carbs: 0, fiber: 0, sodium: 5 },
    metadata: { price: 35, category: "飲品" },
  },
  {
    name: "無糖蕎麥茶",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "杯",
    householdServing: "一杯 (~500ml)",
    calories: 0,
    nutrients: { protein: 0, fat: 0, carbs: 0, fiber: 0, sodium: 5 },
    metadata: { price: 35, category: "飲品" },
  },
  {
    name: "無糖香濃豆漿",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "杯",
    householdServing: "一杯 (~400ml)",
    calories: 120,
    nutrients: { protein: 10, fat: 5, carbs: 8, fiber: 1, sodium: 40 },
    metadata: { price: 25, category: "飲品" },
  },
  {
    name: "有糖香濃豆漿",
    brand: "極限餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "杯",
    householdServing: "一杯 (~400ml)",
    calories: 160,
    nutrients: { protein: 10, fat: 5, carbs: 18, fiber: 1, sodium: 40 },
    metadata: { price: 25, category: "飲品" },
  },
];
