import type { FoodItem } from "./seed-foods";

// Sample foods with common Taiwanese and international foods
// Nutrition per serving based on USDA data
export const sampleFoods: FoodItem[] = [
  {
    name: "白飯",
    brand: null,
    source: "verified" as const,
    servingSize: 200,
    servingUnit: "g",
    householdServing: "1 碗",
    calories: 260,
    nutrients: { protein: 4.4, fat: 0.4, carbs: 57.4, fiber: 0.6, sodium: 2, potassium: 56 },
  },
  {
    name: "雞胸肉",
    brand: null,
    source: "verified" as const,
    servingSize: 100,
    servingUnit: "g",
    householdServing: "1 份",
    calories: 165,
    nutrients: { protein: 31, fat: 3.6, carbs: 0, fiber: 0, sodium: 74, potassium: 256 },
  },
  {
    name: "雞蛋",
    brand: null,
    source: "verified" as const,
    servingSize: 50,
    servingUnit: "g",
    householdServing: "1 顆",
    calories: 72,
    nutrients: { protein: 6.3, fat: 4.8, carbs: 0.4, fiber: 0, sodium: 71, potassium: 69 },
  },
  {
    name: "香蕉",
    brand: null,
    source: "verified" as const,
    servingSize: 118,
    servingUnit: "g",
    householdServing: "1 根 (中)",
    calories: 105,
    nutrients: { protein: 1.3, fat: 0.4, carbs: 27, fiber: 3.1, sodium: 1, potassium: 422 },
  },
  {
    name: "蘋果",
    brand: null,
    source: "verified" as const,
    servingSize: 182,
    servingUnit: "g",
    householdServing: "1 顆 (中)",
    calories: 95,
    nutrients: { protein: 0.5, fat: 0.3, carbs: 25, fiber: 4.4, sodium: 2, potassium: 195 },
  },
  {
    name: "豆漿",
    brand: null,
    source: "verified" as const,
    servingSize: 240,
    servingUnit: "ml",
    householdServing: "1 杯",
    calories: 80,
    nutrients: { protein: 7, fat: 4, carbs: 4, fiber: 1, sodium: 90, potassium: 300 },
  },
  {
    name: "全脂牛奶",
    brand: null,
    source: "verified" as const,
    servingSize: 244,
    servingUnit: "ml",
    householdServing: "1 杯",
    calories: 149,
    nutrients: { protein: 8, fat: 8, carbs: 12, fiber: 0, sodium: 105, potassium: 322 },
  },
  {
    name: "地瓜",
    brand: null,
    source: "verified" as const,
    servingSize: 130,
    servingUnit: "g",
    householdServing: "1 條 (中)",
    calories: 112,
    nutrients: { protein: 2, fat: 0.1, carbs: 26, fiber: 3.8, sodium: 72, potassium: 438 },
  },
  {
    name: "燕麥片",
    brand: null,
    source: "verified" as const,
    servingSize: 40,
    servingUnit: "g",
    householdServing: "1/2 杯",
    calories: 150,
    nutrients: { protein: 5, fat: 2.5, carbs: 27, fiber: 4, sodium: 0, potassium: 143 },
  },
  {
    name: "花椰菜",
    brand: null,
    source: "verified" as const,
    servingSize: 91,
    servingUnit: "g",
    householdServing: "1 杯 (切碎)",
    calories: 31,
    nutrients: { protein: 2.6, fat: 0.3, carbs: 6, fiber: 2.4, sodium: 30, potassium: 288 },
  },
  {
    name: "鮭魚",
    brand: null,
    source: "verified" as const,
    servingSize: 100,
    servingUnit: "g",
    householdServing: "1 片",
    calories: 208,
    nutrients: { protein: 20, fat: 13, carbs: 0, fiber: 0, sodium: 59, potassium: 363 },
  },
  {
    name: "酪梨",
    brand: null,
    source: "verified" as const,
    servingSize: 68,
    servingUnit: "g",
    householdServing: "1/3 顆",
    calories: 109,
    nutrients: { protein: 1.3, fat: 10, carbs: 6, fiber: 4.6, sodium: 5, potassium: 329 },
  },
  {
    name: "豆腐",
    brand: null,
    source: "verified" as const,
    servingSize: 126,
    servingUnit: "g",
    householdServing: "1/2 盒",
    calories: 88,
    nutrients: { protein: 9.2, fat: 5.3, carbs: 2.2, fiber: 0.4, sodium: 10, potassium: 150 },
  },
  {
    name: "全麥麵包",
    brand: null,
    source: "verified" as const,
    servingSize: 43,
    servingUnit: "g",
    householdServing: "1 片",
    calories: 110,
    nutrients: { protein: 5, fat: 1.5, carbs: 20, fiber: 3, sodium: 170, potassium: 100 },
  },
  {
    name: "希臘優格",
    brand: null,
    source: "verified" as const,
    servingSize: 170,
    servingUnit: "g",
    householdServing: "1 杯",
    calories: 100,
    nutrients: { protein: 17, fat: 0.7, carbs: 6, fiber: 0, sodium: 65, potassium: 240 },
  },
  {
    name: "排骨便當",
    brand: null,
    source: "verified" as const,
    servingSize: 450,
    servingUnit: "g",
    householdServing: "1 個",
    calories: 780,
    nutrients: { protein: 35, fat: 25, carbs: 100, fiber: 3, sodium: 1200, potassium: 500 },
  },
  {
    name: "滷肉飯",
    brand: null,
    source: "verified" as const,
    servingSize: 300,
    servingUnit: "g",
    householdServing: "1 碗",
    calories: 510,
    nutrients: { protein: 18, fat: 20, carbs: 65, fiber: 1, sodium: 800, potassium: 300 },
  },
  {
    name: "珍珠奶茶",
    brand: null,
    source: "verified" as const,
    servingSize: 500,
    servingUnit: "ml",
    householdServing: "1 杯 (中)",
    calories: 400,
    nutrients: { protein: 3, fat: 10, carbs: 72, fiber: 0, sodium: 60, potassium: 100 },
  },
  {
    name: "水煮蛋",
    brand: null,
    source: "verified" as const,
    servingSize: 50,
    servingUnit: "g",
    householdServing: "1 顆",
    calories: 78,
    nutrients: { protein: 6.3, fat: 5.3, carbs: 0.6, fiber: 0, sodium: 62, potassium: 63 },
  },
  {
    name: "番薯葉",
    brand: null,
    source: "verified" as const,
    servingSize: 100,
    servingUnit: "g",
    householdServing: "1 份 (炒)",
    calories: 30,
    nutrients: { protein: 3.3, fat: 0.3, carbs: 5.3, fiber: 3.3, sodium: 5, potassium: 502 },
  },
  {
    name: "綜合堅果",
    brand: null,
    source: "verified" as const,
    servingSize: 30,
    servingUnit: "g",
    householdServing: "1 把",
    calories: 175,
    nutrients: { protein: 5, fat: 15, saturatedFat: 2, transFat: 0, carbs: 7, sugar: 1.5, fiber: 2, sodium: 3, potassium: 180 },
  },
];
