import type { FoodItem } from "./seed-foods";

// 越迷 Viet Bites 內湖店 — estimated nutrition per serving
// Estimates based on typical Vietnamese restaurant food nutrition data
export const vietBitesFoods: FoodItem[] = [
  // ========== 麵食 Noodle ==========
  {
    name: "越式爽拌米線",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 450,
    servingUnit: "g",
    householdServing: "1 份",
    calories: 420,
    nutrients: { protein: 18, fat: 8, carbs: 68, fiber: 3, sodium: 850, potassium: 350 },
  },
  {
    name: "河粉雞",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 550,
    servingUnit: "ml",
    householdServing: "1 碗",
    calories: 380,
    nutrients: { protein: 25, fat: 6, carbs: 52, fiber: 1, sodium: 1200, potassium: 400 },
  },
  {
    name: "河粉牛",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 550,
    servingUnit: "ml",
    householdServing: "1 碗",
    calories: 420,
    nutrients: { protein: 28, fat: 10, carbs: 52, fiber: 1, sodium: 1300, potassium: 450 },
  },
  {
    name: "酸辣牛河粉",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 550,
    servingUnit: "ml",
    householdServing: "1 碗",
    calories: 450,
    nutrients: { protein: 28, fat: 12, carbs: 55, fiber: 2, sodium: 1400, potassium: 480 },
  },

  // ========== 越式法國麵包 Banh mi (大 L) ==========
  {
    name: "炙燒蒜香豬肉法國麵包",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 320,
    servingUnit: "g",
    householdServing: "1 份 (大)",
    calories: 480,
    nutrients: { protein: 22, fat: 14, carbs: 62, fiber: 3, sodium: 980, potassium: 350 },
  },
  {
    name: "綜合火腿法國麵包",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 320,
    servingUnit: "g",
    householdServing: "1 份 (大)",
    calories: 500,
    nutrients: { protein: 20, fat: 18, carbs: 60, fiber: 3, sodium: 1100, potassium: 300 },
  },
  {
    name: "炙燒香茅雞腿法國麵包",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 320,
    servingUnit: "g",
    householdServing: "1 份 (大)",
    calories: 460,
    nutrients: { protein: 24, fat: 12, carbs: 60, fiber: 3, sodium: 950, potassium: 380 },
  },
  {
    name: "台式經典炸雞法國麵包",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 320,
    servingUnit: "g",
    householdServing: "1 份 (大)",
    calories: 550,
    nutrients: { protein: 22, fat: 22, carbs: 62, fiber: 3, sodium: 1050, potassium: 320 },
  },
  {
    name: "清爽蔬食法國麵包",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 300,
    servingUnit: "g",
    householdServing: "1 份 (大)",
    calories: 380,
    nutrients: { protein: 10, fat: 8, carbs: 64, fiber: 5, sodium: 780, potassium: 400 },
  },
  {
    name: "港式脆皮燒肉法國麵包",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 320,
    servingUnit: "g",
    householdServing: "1 份 (大)",
    calories: 530,
    nutrients: { protein: 20, fat: 20, carbs: 62, fiber: 3, sodium: 1050, potassium: 320 },
  },
  {
    name: "鮮蝦火腿法國麵包",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 320,
    servingUnit: "g",
    householdServing: "1 份 (大)",
    calories: 470,
    nutrients: { protein: 24, fat: 14, carbs: 60, fiber: 3, sodium: 1100, potassium: 350 },
  },

  // ========== 越式春捲 Rice Paper Roll ==========
  {
    name: "炙燒蒜香豬肉春捲",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 200,
    servingUnit: "g",
    householdServing: "1 份 (2捲)",
    calories: 260,
    nutrients: { protein: 14, fat: 6, carbs: 38, fiber: 2, sodium: 580, potassium: 280 },
  },
  {
    name: "炙燒香茅雞腿春捲",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 200,
    servingUnit: "g",
    householdServing: "1 份 (2捲)",
    calories: 250,
    nutrients: { protein: 15, fat: 5, carbs: 36, fiber: 2, sodium: 560, potassium: 300 },
  },
  {
    name: "清爽蔬食春捲",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 200,
    servingUnit: "g",
    householdServing: "1 份 (2捲)",
    calories: 200,
    nutrients: { protein: 5, fat: 2, carbs: 40, fiber: 3, sodium: 420, potassium: 320 },
  },
  {
    name: "台式經典炸雞春捲",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 200,
    servingUnit: "g",
    householdServing: "1 份 (2捲)",
    calories: 310,
    nutrients: { protein: 14, fat: 12, carbs: 36, fiber: 2, sodium: 620, potassium: 260 },
  },
  {
    name: "炸春捲",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 150,
    servingUnit: "g",
    householdServing: "1 份 (4-5個)",
    calories: 320,
    nutrients: { protein: 10, fat: 16, carbs: 32, fiber: 2, sodium: 650, potassium: 200 },
  },
  {
    name: "港式脆皮燒肉春捲",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 200,
    servingUnit: "g",
    householdServing: "1 份 (2捲)",
    calories: 300,
    nutrients: { protein: 14, fat: 10, carbs: 36, fiber: 2, sodium: 620, potassium: 270 },
  },
  {
    name: "鮮蝦火腿春捲",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 200,
    servingUnit: "g",
    householdServing: "1 份 (2捲)",
    calories: 260,
    nutrients: { protein: 16, fat: 6, carbs: 36, fiber: 2, sodium: 640, potassium: 290 },
  },

  // ========== 沙拉 Salad ==========
  {
    name: "木瓜沙拉",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 250,
    servingUnit: "g",
    householdServing: "1 份",
    calories: 180,
    nutrients: { protein: 5, fat: 7, carbs: 26, fiber: 4, sodium: 720, potassium: 380 },
  },

  // ========== 湯品 Soup ==========
  {
    name: "味噌湯",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 300,
    servingUnit: "ml",
    householdServing: "1 碗",
    calories: 60,
    nutrients: { protein: 4, fat: 2, carbs: 6, fiber: 1, sodium: 900, potassium: 200 },
  },
  {
    name: "河粉湯（無肉）",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 500,
    servingUnit: "ml",
    householdServing: "1 碗",
    calories: 220,
    nutrients: { protein: 5, fat: 3, carbs: 42, fiber: 1, sodium: 1000, potassium: 200 },
  },

  // ========== 飲品 Beverage ==========
  {
    name: "冷泡茶",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 500,
    servingUnit: "ml",
    householdServing: "1 杯",
    calories: 5,
    nutrients: { protein: 0, fat: 0, carbs: 1, fiber: 0, sodium: 5, potassium: 40 },
  },
  {
    name: "越南咖啡",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 240,
    servingUnit: "ml",
    householdServing: "1 杯",
    calories: 180,
    nutrients: { protein: 3, fat: 5, carbs: 30, fiber: 0, sodium: 50, potassium: 150 },
  },
  {
    name: "泰式奶茶",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 500,
    servingUnit: "ml",
    householdServing: "1 杯",
    calories: 280,
    nutrients: { protein: 4, fat: 8, carbs: 48, fiber: 0, sodium: 80, potassium: 200 },
  },
  {
    name: "椰子水",
    brand: "越迷 Viet Bites",
    source: "user" as const,
    servingSize: 330,
    servingUnit: "ml",
    householdServing: "1 瓶",
    calories: 60,
    nutrients: { protein: 1, fat: 0, carbs: 14, fiber: 0, sodium: 65, potassium: 400 },
  },
];
