import type { FoodItem } from "./seed-foods";

// 享蒔健康餐盒 — 台北內湖/南京/南港
// 餐盒含季節蔬菜 (6 種)、水煮蛋、三色飯 (白飯+糙米+黑米)
// 營養為估算值（健康餐盒典型組成）
// Menu from Uber Eats / Fooday
export const xiangShiFoods: FoodItem[] = [
  {
    name: "紐奧良雞胸肉 餐盒",
    brand: "享蒔健康餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~450g)",
    calories: 650,
    nutrients: { protein: 45, fat: 18, carbs: 72, fiber: 6, sodium: 850 },
    metadata: { price: 170, category: "雞胸肉系列" },
  },
  {
    name: "咖哩雞胸肉 餐盒",
    brand: "享蒔健康餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~450g)",
    calories: 650,
    nutrients: { protein: 44, fat: 19, carbs: 70, fiber: 6, sodium: 880 },
    metadata: { price: 170, category: "雞胸肉系列" },
  },
  {
    name: "辣味雞胸肉 餐盒",
    brand: "享蒔健康餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~450g)",
    calories: 650,
    nutrients: { protein: 45, fat: 18, carbs: 72, fiber: 6, sodium: 900 },
    metadata: { price: 170, category: "雞胸肉系列" },
  },
  {
    name: "照燒雞腿 餐盒",
    brand: "享蒔健康餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~460g)",
    calories: 757,
    nutrients: { protein: 42, fat: 25, carbs: 78, fiber: 5, sodium: 920 },
    metadata: { price: 220, category: "雞腿系列" },
  },
  {
    name: "舒肥板腱牛 餐盒",
    brand: "享蒔健康餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~450g)",
    calories: 657,
    nutrients: { protein: 43, fat: 20, carbs: 70, fiber: 5, sodium: 850 },
    metadata: { price: 235, category: "牛肉系列" },
  },
  {
    name: "泡菜豬肉 餐盒",
    brand: "享蒔健康餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~450g)",
    calories: 620,
    nutrients: { protein: 35, fat: 20, carbs: 72, fiber: 5, sodium: 950 },
    metadata: { price: 185, category: "豬肉系列" },
  },
  {
    name: "舒肥海鹽松阪豚 餐盒",
    brand: "享蒔健康餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~450g)",
    calories: 680,
    nutrients: { protein: 35, fat: 25, carbs: 70, fiber: 5, sodium: 820 },
    metadata: { price: 200, category: "豬肉系列" },
  },
  {
    name: "舒肥炙燒板腱牛 餐盒",
    brand: "享蒔健康餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~450g)",
    calories: 670,
    nutrients: { protein: 44, fat: 22, carbs: 70, fiber: 5, sodium: 860 },
    metadata: { price: 235, category: "牛肉系列" },
  },
  {
    name: "舒肥香蒜鯛魚 餐盒",
    brand: "享蒔健康餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~440g)",
    calories: 580,
    nutrients: { protein: 38, fat: 14, carbs: 72, fiber: 6, sodium: 780 },
    metadata: { price: 195, category: "魚類系列" },
  },
  {
    name: "舒肥炙燒鮭魚 餐盒",
    brand: "享蒔健康餐盒",
    source: "verified",
    servingSize: 1,
    servingUnit: "盒",
    householdServing: "一個餐盒 (~440g)",
    calories: 650,
    nutrients: { protein: 40, fat: 22, carbs: 68, fiber: 5, sodium: 780 },
    metadata: { price: 235, category: "魚類系列" },
  },
];
